batch_size: 32
checkpoint_dir: checkpoints/20230225T165607744822-convnext
checkpoint_freq: 1000
checkpoint_path: checkpoints/20230225T165607744822-convnext/checkpoint_00009000.pth.tar
checkpoints_dir: checkpoints
collision_penalty: 15000
discount_factor: 0.99
experiment_name: convnext
exploration_reward: 1
exploration_timesteps: 3500
final_exploration: 0.1
fixed_step_size: null
grad_norm_clipping: 10
inactivity_cutoff: 100
learning_rate: 0.001
learning_starts: 1000
log_dir: logs/convnext-cosine-warmup-9000
logs_dir: logs
min_lr: 5e-7
ministep_size: 0.25
model_path: checkpoints/20230225T165607744822-convnext/model_00009000.pth.tar
nonmovement_penalty: 15000
num_cubes: 1
num_input_channels: 4
obstacle_config: large_columns
partial_rewards_scale: 2.0
policy_type: convnext
position_channel_scale: 0.25
random_seed: null
replay_buffer_size: 6000
room_length: 3.0
room_width: 3.0
run_name: convnext-cosine-warmup-9000
shortest_path_channel_scale: 0.25
steering_commands_num_turns: 4
target_update_freq: 1000
total_timesteps: 35000
use_double_dqn: true
use_opt_rule: 2
use_position_channel: false
use_shortest_path_channel: true
use_shortest_path_movement: true
use_shortest_path_partial_rewards: true
use_steering_commands: false
use_visit_frequency_channel: true
weight_decay: 0.002
state_type: convnext