# Mostly copied from opt-vfm-sam.yml with small tweaks
batch_size: 32
checkpoint_dir:
checkpoint_freq: 3000
checkpoint_path: null
checkpoints_dir: checkpoints
collision_penalty: 15000
exploration_reward: 1
discount_factor: 0.99
experiment_name: large_columns_sigmoid
exploration_timesteps: 3000
final_exploration: 0.1
fixed_step_size: null
grad_norm_clipping: 10
inactivity_cutoff: 100
learning_rate: 0.01
learning_starts: 1000
log_dir:
logs_dir: logs
ministep_size: 0.25
model_path: null
nonmovement_penalty: 15000
num_cubes: 1
num_input_channels: 2
obstacle_config: large_columns
policy_type: dense_action_space
partial_rewards_scale: 2.0
position_channel_scale: 0.25
random_seed: null
replay_buffer_size: 6000
room_length: 3.0
room_width: 3.0
run_name:
shortest_path_channel_scale: 0.25
steering_commands_num_turns: 4
target_update_freq: 1000
total_timesteps: 25000
use_double_dqn: true
use_position_channel: false
use_visit_frequency_channel: true
use_ivfm: true
use_shortest_path_channel: true
use_shortest_path_movement: true
use_shortest_path_partial_rewards: true
use_boundary_gradient_channel: false
use_steering_commands: false
use_opt_rule: 2
weight_decay: 0.0001
