batch_size: 32
checkpoint_dir: 
checkpoint_freq: 1000
checkpoints_dir: checkpoints
collision_penalty: 10
discount_factor: 0.99
experiment_name: large_columns_vfm_hyperbolic
exploration_reward: 1
exploration_timesteps: 3000
final_exploration: 0.1
fixed_step_size: null
grad_norm_clipping: 10
inactivity_cutoff: 100
learning_rate: 0.01
learning_starts: 33
log_dir: 
logs_dir: logs
ministep_size: 0.25
nonmovement_penalty: 10
num_cubes: 1
num_input_channels: 4
obstacle_config: large_columns
partial_rewards_scale: 2.0
policy_type: dense_action_space
position_channel_scale: 0.25
random_seed: null
replay_buffer_size: 6000
room_length: 3.0
room_width: 3.0
run_name: benchmark-with-original-vfm-model-hyperbolic-state
state_type: hyperbolic
shortest_path_channel_scale: 0.25
steering_commands_num_turns: 4
target_update_freq: 1000
total_timesteps: 35000
use_double_dqn: true
use_opt_rule: 2
step_limit: 1600 # Increased to allow far traversals
use_position_channel: false
use_shortest_path_channel: true
use_shortest_path_movement: true
use_shortest_path_partial_rewards: true
use_steering_commands: false
use_visit_frequency_channel: true
weight_decay: 0.0001

hyperbolic_zoom: 3
checkpoint_path: checkpoints/20221211T173207194045-large_columns_vfm_hyperbolic/checkpoint_00001000.pth.tar
model_path: checkpoints/20221211T173207194045-large_columns_vfm_hyperbolic/model_00001000.pth.tar

